### ISSUE TITLE
[BUG] Beat and Glyphs desync over time

### ISSUE THREAD

**Issue by SebiAi** [Krishnagopal-Sinha/better-nothing-glyph-composer#5]
Hi, I tried your project and I noticed that the Glyphs and the beats seem to drift apart over time.

I verified this by generating a metronome audio file that ticks every two seconds and composed it with your tool. Download [here](https://filebin.net/6z1wopzhddae5gc1/glyph_1723884225779.ogg) - expires in 6 days. You can verify this by downloading the composition and playing it back ***in the Ringtone Settings menu***.

Why does this happen?:
When you generate the csv data, each line corresponds to 16.666ms and not 16ms (60Hz) - see the updated documentation of mine [here](https://github.com/SebiAi/custom-nothing-glyph-tools/blob/main/docs/8_Technical%20Details.md).

This should merit a "major" version increase of the app if you are using Semantic Versioning.
I think it would also be useful to indicate this change in the metadata of the compositions, e.g.: changing the `ALBUM` tag from `custom` to `BNGC v{MAJOR}`, where `{MAJOR}` should be replaced with the major version number (Semantic Versioning). This change would let tools like my Glyph Tools know what compositions are with this desync and which not.

**Comment by Krishnagopal-Sinha** [comment]
Hii, thanks for trying out this project!
I am not that good with words but thank you so much for writing an informative issue like this, I will be looking into this during this weekend! 
Rest assured I will take all your advice into accounts and follow up with you if I have any further questions.

**Comment by Krishnagopal-Sinha** [comment]
Hii @SebiAi, I have made the changes that address this issue, and fix is now live. The album has been set to reflect 'BNGC v1' in generated file's metadata. While yes the ringtone now is properly synced, I am seeing that official composer app is out of sync. Is this expected or did I goof something up?

**Comment by SebiAi** [comment]
You also need to set the correct `COMPOSER` tag.
For Phone (1): `v1-Spacewar Glyph Composer`

See the linked "Technical Details" in the original post.

**Comment by Krishnagopal-Sinha** [comment]
I see, my bad, It's resolved now, thanks 🙏
I had just skimmed through the docs as I had read the old one before, thus I missed that composer detail.
Feel free to reopen this issue if there's any more concerns regarding this. I'm off to read the docs in detail again 😁
