### ISSUE TITLE
[BUG] Error loading `.ogg` audio file on Firefox

### ISSUE THREAD

**Issue by SebiAi** [Krishnagopal-Sinha/better-nothing-glyph-composer#6]
When trying to load an audio file with the `opus` codec and `.ogg` extension **in the Firefox Browser**, the web app displays a black screen and gives error messages in the console.

## What happens
* The screen turns black
* These appear in the console log:
![image](https://github.com/user-attachments/assets/e976d36b-ef0b-4b55-9ab3-326cae59d475)

## What I expect to happen
The audio loads fine, like on Chrome

## Additional Info
\-

## Browser details
> Google Chrome Version 127.0.6533.119 (Official Build) (64-Bit)
> Firefox (for Linux Mint: mint-001 - 1.0) 129.0 (64-Bit)

**Comment by Krishnagopal-Sinha** [comment]
Resolved in latest update.
